apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scrumlr-fullname" .Values.livequery }}
  labels: 
    {{- include "selectorLabels" .Values.livequery | nindent 6}}
    {{- include "labels" . | nindent 6}}
{{- if .Values.livequery.config }}
data:
{{ toYaml .Values.livequery.config | indent 2 }}
{{- end}}
