apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scrumlr-fullname" .Values.livequery }}
  labels: 
    {{- include "selectorLabels" .Values.livequery | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
spec:
  replicas: {{ .Values.livequery.replicas | default 1 }} 
  selector:
    matchLabels:
      {{- include "selectorLabels" .Values.livequery | nindent 6 }}
  template:
    metadata:
      labels: 
        {{- include "selectorLabels" .Values.livequery | nindent 8 }}  
    spec:
      containers:
        - name: {{ include "scrumlr-fullname" .Values.livequery }}
          image: {{ .Values.livequery.image }}
          imagePullPolicy: IfNotPresent 
          envFrom:
            - configMapRef: 
                name: {{ include "scrumlr-fullname" .Values.livequery }}
            - secretRef:
                name: {{ include "scrumlr-fullname" .Values.livequery }}
          ports:
            - name: livequery 
              containerPort: 4000 
          livenessProbe:
            tcpSocket:
              port: livequery 
            initialDelaySeconds: 40
            periodSeconds: 20
          readinessProbe: 
            tcpSocket:
              port: livequery 
            initialDelaySeconds: 10 
            periodSeconds: 10
      restartPolicy: Always 
