apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "scrumlr-fullname" .Values.livequery }}
  labels: 
    {{- include "selectorLabels" .Values.livequery | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.cert.enabled }}
    cert-manager.io/cluster-issuer: {{if .Values.cert.prod}}"letsencrypt-production"{{ else }}"letsencrypt-staging"{{ end }}
    {{- end }}
spec:
  {{- if and .Values.cert.enabled .Values.hostname}}
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName:  {{ .Values.cert.name }}
 {{- end }}
  rules:
  - http:
      paths:
      - path: /ws 
        pathType: Prefix
        backend:
          service:
            name: {{ include "scrumlr-fullname" .Values.livequery }}
            port:
              number: 4000 
  {{- if .Values.hostname }} 
    host: {{ .Values.hostname }}
  {{- end}}
