apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrumlr-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrumlr-server
  template:
    metadata:
      labels: 
        app: scrumlr-server
    spec:
      containers:
        - name: scrumlr-server
          image: scrumlr-parse-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: scrumlr-server-configmap
            - secretRef:
                name: scrumlr-server-secrets
      restartPolicy: Always