apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-configmap
  namespace: {{ .Release.Namespace }}
data:
  SCRUMLR_SERVER_PORT: {{ .Values.backend.config.serverPort | quote }}
  SCRUMLR_BASE_PATH: {{ .Values.backend.config.basePath | quote }}
  SCRUMLR_SERVER_NATS_URL: {{ .Values.backend.config.natsUrl | quote }}
  {{- range $key, $val := .Values.backend.extraConfig }}
  {{ $key | upper }}: {{ $val | quote }}
  {{- end }}