apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scrumlr-fullname" .Values.server }}
  labels: 
    {{- include "selectorLabels" .Values.server | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
spec:
  replicas: {{ .Values.server.replicas | default 1 }} 
  selector:
    matchLabels:
      {{- include "selectorLabels" .Values.server | nindent 6 }}
  template:
    metadata:
      labels: 
        {{- include "selectorLabels" .Values.server | nindent 8 }}
    spec:
      containers:
        - name: {{ include "scrumlr-fullname" .Values.server }}
          image: {{ .Values.server.image }}
          imagePullPolicy: IfNotPresent 
          ports:
            - name: server 
              containerPort: 4000 
          envFrom:
            - configMapRef:
                name: {{ include "scrumlr-fullname" .Values.server }}
            - secretRef:
                name: {{ include "scrumlr-fullname" .Values.server }}
          livenessProbe: 
            httpGet:
              path: /api/health
              port: server 
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe: 
            httpGet:
              path: /api/users
              port: server 
              httpHeaders:
              - name: X-Parse-Application-Id
                value: Scrumlr
            initialDelaySeconds: 10 
            periodSeconds: 5
            timeoutSeconds: 5
      restartPolicy: Always 
