contact_links:
  - name: ðŸš€ Feature Request
    url: https://github.com/inovex/scrumlr.io/discussions/new?category=proposals
    about:
      We appreciate you taking the time to improve Scrumlr with your ideas, but we
      use the Discussions for this instead of the issues tab ðŸ™‚.
  - name: ðŸ’¬ Get Help
    url: https://github.com/inovex/scrumlr.io/discussions/new?category=q-a
    about:
      If you can't get something to work the way you expect, open a question in
      the Scrumlr discussions.