name: "Deployment health check"
description: |
  "Changes the DNS to our own (since the DNS dev-cluster records are fastest available here) and performes a healthcheck"

runs:
  steps:
    - name: Change DNS Server
      run: |
        sudo sed -i 's/#DNS=/DNS=ns2.fra.cloud.inovex.io/' /etc/systemd/resolved.conf
        sudo systemctl daemon-reload
        sudo systemctl restart systemd-networkd
        sudo systemctl restart systemd-resolved
        dig +short github.com

    - name: Wait for cluster to become healthy
      id: wait-for-cluster
      env:
        BASE_URL: https://${{ github.event.pull_request.number }}.development.scrumlr.fra.ics.inovex.io
      run: |
        # Disable cancelation of script on first error (since cluster might be not reachable -> curl would return error code != 0)
        set +e

        retry=1
        max_retries=4
        until [ $retry -gt $max_retries ]
        do
          response=$(curl -s -k -o /dev/null -w "%{http_code}" "$BASE_URL/api/health")
          if [ $response = "204" ]; then
            echo "Cluster is healthy! Continuing..."
            break
          fi
          echo "Cluster is not responding. Retrying in $((5 * retry)) seconds..."
          sleep $((5 * retry))
          retry=$((retry + 1))
        done

        set -e # re-enable cancelation on error
        
        if [ $response != "204" ]; then
          echo "::error::Cluster is not responding after $max_retries attempts."
          exit 1 
        fi   