apiVersion: v2
name: scrumlr
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.1"
dependencies:
- name: mongodb
  version: 10.23.*
  repository: https://charts.bitnami.com/bitnami
  alias: mongodb