name: Cleanup Feature Branch Deployment

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  cluster-cleanup:
    name: Clean Up Cluster Resources
    runs-on: self-hosted
    steps:
      - name: scrumlr
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          helm uninstall scrumlr $PR_NUMBER -n scrumlr-$PR_NUMBER
          kubectl delete ns scrumlr-$PR_NUMBER
